name: Release
on:
  push:
    tags:
      - "v*"
env:
  FORCE_COLOR: 2
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
        include:
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
      fail-fast: false
    name: Release,${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: https://registry.npmmirror.com/

      - name: Install dependencies
        run: pnpm i

      - name: Run lint
        run: pnpm lint && cd packages/webpage && pnpm check

      - name: Build ts, page, and release app
        run: cd packages/electron && pnpm build-cli && pnpm release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

